[project]
name = "local-llm"
version = "0.1.0"
description = ""
authors = [
    {name = "ekb",email = "ekb.dev.ai@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai (>=2.29.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
